@startuml ゲーム遷移

title ゲーム遷移

[*] --> 参加待機

参加待機 : 相手がいない場合に待機
参加待機 -[#blue]-> 承認待機 : サーバ通知

承認待機 : 対戦相手の承認
承認待機 --> 承認待機 : 承認
承認待機 -[#blue]-> ゲーム中 : サーバ通知（相手が承認）
承認待機 -[#blue]-> 参加待機 : サーバ通知（相手が否認）

state ゲーム中 {
  [*] --> 順番待機
  順番待機 : サーバが手番を計算
  順番待機 -[#blue]-> 自分の番 : サーバ通知（自分の番）
  順番待機 -[#blue]-> 相手の番 : サーバ通知（相手の番）
  順番待機 -[#blue]-> [*] : サーバ通知（終了）

  自分の番 : 手番が自分の状態
  自分の番 --> 順番待機 : 碁石を打つ

  相手の番 : 手番が対戦相手の状態
  相手の番 -[#blue]-> 順番待機 : サーバ通知
}
ゲーム中 --> 終了 : ゲーム終了

終了 : ゲーム終了状態
終了 --> 継続待機 : ゲーム継続
終了 --> [*] : ゲーム離脱

継続待機 -[#blue]-> 参加待機 : サーバ通知（相手が離脱）
継続待機 -[#blue]-> ゲーム中 : サーバ通知（相手が承認）

@enduml
