@startuml 画面遷移

title 画面遷移

[*] --> ポータル : アクセス

state ポータル {
  [*] --> トップ
  トップ : トップ画面
  トップ --> ログイン : ログイン
  トップ --> 新規登録 : 新規登録
  トップ --> [*] : ゲストログイン

  新規登録 : アカウント新規登録画面
  新規登録 --> ログイン : ログイン
  新規登録 --> 新規登録 : 登録失敗
  新規登録 --> [*] : 登録成功

  ログイン : ログイン画面
  ログイン --> 新規登録 : 新規登録
  ログイン --> ログイン : ログイン失敗
  ログイン --> トップ : 戻る
  ログイン --> [*] : ログイン成功
}
ポータル --> 部屋一覧 : アカウント決定

部屋一覧 : サーバから取得した部屋一覧をリスト表示
部屋一覧 : リストはページング

部屋一覧 --> 部屋詳細 : 詳細
部屋一覧 --> 部屋 : 参加
部屋一覧 --> ポータル : ログアウト

部屋詳細 : 部屋の参加者・ルールを表示
部屋詳細 --> 部屋一覧 : 閉じる
部屋詳細 --> 部屋 : 参加

部屋 : オセロ盤面が表示
部屋 --> 部屋一覧 : 抜ける

@endum
