@startuml ゲーム開始

title ゲーム開始

クライアント1 -> サーバ: 部屋一覧取得
クライアント1 <-- サーバ: 部屋一覧

クライアント1 -> サーバ: 部屋作成
クライアント1 <-- サーバ: 待機合図

クライアント2 -> サーバ: 部屋一覧取得
クライアント2 <-- サーバ: 部屋一覧
クライアント2 -> サーバ: 部屋参加

クライアント1 <-- サーバ: 参加者通知
クライアント2 <-- サーバ: 参加者通知

クライアント1 -> サーバ: 承認
クライアント2 -> サーバ: 承認

== ゲーム開始 ==

クライアント1 <-- サーバ: 手番通知
クライアント2 <-- サーバ: 手番通知

@enduml
