@startuml ゲーム中

title ゲーム中

== ゲーム開始 ==

クライアント1 <-- サーバ: 手番通知
クライアント2 <-- サーバ: 手番通知

loop どちらも置けない状態になるまで
  alt 先攻が置ける状態
    クライアント1 -> サーバ: 碁石を打つ
  else 置けない状態
    クライアント1 -> サーバ: パス宣言
  end

  クライアント1 <-- サーバ: 状態通知
  クライアント2 <-- サーバ: 状態通知

  alt 後攻が置ける状態
    クライアント2 -> サーバ: 碁石を打つ
  else 置けない状態
    クライアント2 -> サーバ: パス宣言
  end

  クライアント1 <-- サーバ: 状態通知
  クライアント2 <-- サーバ: 状態通知
end

== ゲーム終了 ==

クライアント1 <-- サーバ: ゲーム結果
クライアント2 <-- サーバ: ゲーム結果

@enduml
