@startuml ゲーム再スタート

title ゲーム再スタート

== ゲーム終了 ==

クライアント1 <-- サーバ: ゲーム結果
クライアント2 <-- サーバ: ゲーム結果

クライアント1 -> サーバ: 継続通知
クライアント1 <-- サーバ: 継続通知
クライアント2 <-- サーバ: 継続通知

クライアント2 -> サーバ: 継続通知
クライアント1 <-- サーバ: 継続通知
クライアント2 <-- サーバ: 継続通知

クライアント1 <-- サーバ: 再スタート通知
クライアント2 <-- サーバ: 再スタート通知

== ゲーム開始 ==

クライアント1 <-- サーバ: 手番通知
クライアント2 <-- サーバ: 手番通知

@enduml
