@startuml ゲーム再スタート

title ゲーム再スタート

== ゲーム終了 ==

クライアント1 <-- サーバ: ゲーム結果
クライアント2 <-- サーバ: ゲーム結果

クライアント1 -> サーバ: ゲーム継続
クライアント1 <-- サーバ: 継続通知
クライアント2 <-- サーバ: 継続通知

クライアント2 -> サーバ: ゲーム終了
クライアント1 <-- サーバ: 終了通知
クライアント2 <-- サーバ: 終了通知

@enduml
